### ISSUE TITLE
SeargeSDXLImage2ImageSampler.sample() got an unexpected keyword argument 'softness'

### ISSUE THREAD

**Issue by unbruitsourd** [SeargeDP/SeargeSDXL#17]
I get this error when the "HiRes Fix Sampler" node is rendered.
<img width="666" alt="Capture d’écran 2023-08-03 001157" src="https://github.com/SeargeDP/SeargeSDXL/assets/74782144/8c90af68-af45-421e-8a26-68d7c88aa093">

**Comment by SeargeDP** [comment]
Thanks for reporting it, should be fixed with the v3.0a hotfix. Depending on how you installed this extension, either download the newly released file or do a git pull

**Comment by GalaxyTimeMachine** [comment]
I updated and still see this same error. The filename is still 3.0, should it be 3.0a?
[Searge-SDXL-Reborn-v3_0.json](https://github.com/SeargeDP/SeargeSDXL/blob/main/workflow/Searge-SDXL-Reborn-v3_0.json)

**Comment by GalaxyTimeMachine** [comment]
I see you've updated again, and this is now working for me. Thanks for the quick turnaround!

**Comment by SeargeDP** [comment]
ok, closing as solved
