### ISSUE TITLE
Search menu so loooooong !

### ISSUE THREAD

**Issue by rickcx** [SeargeDP/SeargeSDXL#22]
![截图 2023-08-04 09-20-41](https://github.com/SeargeDP/SeargeSDXL/assets/18411743/717dd7ab-3dc9-46b0-88b2-711c672b5098)
After install SeargeSDXL ,my search menu like this. Unistall SeargeSDXL the search menu fixed.

**Comment by Piscabo** [comment]
The dropdown search is also not working have to scroll to find a model:
![image](https://github.com/SeargeDP/SeargeSDXL/assets/123719842/90836392-5100-4a87-8330-7eea58d986d8)
Lora, Checkpoint, Upscaler, etc
The new Workflow is great, apart from those.

**Comment by SeargeDP** [comment]
Is the search menu size issue fixed when you update to v3.1?

**Comment by rickcx** [comment]
After update to v3.1, the search menu size issue not fixed. Same as the previous version.

**Comment by rickcx** [comment]
> Is the search menu size issue fixed when you update to v3.1?

After update to v3.1, the search menu size issue not fixed. Same as the previous version.

**Comment by SeargeDP** [comment]
Ok, I think I finally fixed it for the next update. I've pushed the fixes to my dev branch already in case anyone wants to test them before the update is released

**Comment by Piscabo** [comment]
> Ok, I think I finally fixed it for the next update. I've pushed the fixes to my dev branch already in case anyone wants to test them before the update is released

Where is the Dev Branch? The update I just ran still does not allow a search...

**Comment by SeargeDP** [comment]
The development branch is in this repository and is conveniently called `dev`. Just be aware that it's usually untested in-development stuff on there, so if you don't want to risk installing something that may be in a broken state better wait for the next update to be released

**Comment by SeargeDP** [comment]
This should be fixed (for real this time) in the upcoming version 3.2 update

**Comment by SeargeDP** [comment]
I got feedback that it's fixed in the latest update, so I'm closing this now.
